apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - aws-ebs-csi-driver.yaml
  - ingress-nginx.yaml
  - metrics-server.yaml
  - cloudnative-pg.yaml
  - gitea-charts.yaml
  - aws-efs-csi-driver.yaml
