apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-sc
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-045cbd5a64e172aed
  directoryPerms: "700"
reclaimPolicy: Delete
volumeBindingMode: Immediate
